---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "chartwide-annotations" . | nindent 4 }}
    {{- include "chartwide-additional-annotations" . | nindent 4 }}
  name: {{ .Release.Name }}-basic-auth
type: Opaque
data:
  auth: {{ .Values.basicAuth | b64enc }}

{{- if not .Values.certManagerCertificate }}
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- include "chartwide-annotations" . | nindent 4 }}
    {{- include "chartwide-additional-annotations" . | nindent 4 }}
  name: {{ .Release.Name }}-http-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
  {{- if .Values.ingress.tls.ca }}
  ca.crt: {{ .Values.ingress.tls.ca | b64enc }}
  {{- end }}
{{- end}}